### ISSUE TITLE
Bureau de l'urbaniste

### ISSUE THREAD

**Issue by NyanKiyoshi** [Urbanotopus/urbanotopus#2]
- Avoir un téléphone et une radio posés sur un bureau sur lesquels l'utilisateur peut cliquer pour accèder au contenu de l'objet ;
- ~~Avoir la possibilité de bouger la caméra avec la souris.~~ **Fonctionnalité supprimée car nous sommes dans une scène statique qui attend à ce que l'utilisateur clique sur un élément à l'écran. Nous ne voulons donc pas que l'utilisateur puisse regarder autour de lui.**

![preview](https://user-images.githubusercontent.com/6186720/46625441-4e779d80-cb34-11e8-9dc9-b866d1418328.png)

**Comment by NyanKiyoshi** [comment]
Preview:
![image](https://user-images.githubusercontent.com/6186720/46918336-59697c80-cfd1-11e8-9116-942356c9458d.png)

**Comment by Razafa** [comment]
issue #2 à changer parce que, paraît-il, le bureau ne correspond pas à la charte graphique.

**Comment by NyanKiyoshi** [comment]
Comment ça ?

**Comment by NyanKiyoshi** [comment]
J'aurais préféré que tu ouvres un nouveau ticket expliquant le souci, ce ticket est fermé car il a été réglé.

**Comment by hugovain** [comment]
On en avais déjà parlé, le bureau jure furieusement avec le reste du jeu

**Comment by NyanKiyoshi** [comment]
S'il s'avère que le bureau final ne répond pas à la charte graphique (qui n'existe pas, libre à vous d'ouvrir un ticket pour la création d'une charte graphique), dans ce cas, on créera une tâche `P3` pour adapter le bureau avec le reste du jeu.

Pour l'instant, je ferme ce ticket qui parle de la création et de l'ajout du bureau de l'urbaniste.

@Razafa sois libre d'ouvrir un nouveau ticket "Le bureau de l'urbaniste ne répond pas à la charte graphique", où on pourra en discuter plus en profondeur.

En attendant, cette discussion est hors-sujet pour ce ticket, il reste donc fermé.
